fr:
  inherit: base
es:
  inherit: base
ja:
  inherit: base
zh:
  inherit: base
it:
  inherit: base
base:
  targets:
    # - 'latex'
    # - 'json'
    # - 'man'
    # - 'epub'
    # - 'singlehtml'
    - 'html'
    - 'dirhtml'
  links: []
  doc-root: []
  branch-root: []
