#source: /installation.txt
#truncate:
#  end-before: "Installation Guides"
#transform:
#  - regex: ':doc:`/release-notes`'
#    replace: ':manual:`Release Notes </release-notes>`'
#append: |
#  .. include:: /includes/toc/dfn-list-install-on-linux-landing.rst
#  .. include:: /includes/toc/install-on-linux-landing.rst
#
#  .. include:: /includes/toc/dfn-list-installation-osx.rst
#  .. include:: /includes/toc/installation-osx.rst
#
#  .. include:: /includes/toc/dfn-list-installation-windows.rst
#  .. include:: /includes/toc/installation-windows.rst
---
source: includes/toc-install-on-linux-landing.yaml
transform:
  - regex: "file: /administration/install-on-linux"
    replace: "file: /tutorial/install-on-linux"
---
source: administration/install-on-linux.txt
target: tutorial/install-on-linux.rst
transform:
  - regex: "For systems without supported packages.*"
    replace: ""
  - regex: "Installation tutorial."
    replace: ""
---
source: tutorial/install-mongodb-on-red-hat-centos-or-fedora-linux.txt
target: tutorial/install-mongodb-on-red-hat-centos-or-fedora-linux.rst
transform:
  regex: ":doc:`default ports </reference/default-mongodb-port>`."
  replace: ":manual:`default ports </reference/default-mongodb-port>`."
---
source: tutorial/install-mongodb-on-windows.txt
target: tutorial/install-mongodb-on-windows.rst
transform:
  - regex: ":doc:`/core/security`"
    replace: ":manual:`Security Concepts </core/security>`"
  - regex: ":doc:`/reference/method"
    replace: ":manual:`MongoDB Shell Methods </reference/methods>`"
  - regex: ":doc:`(.*) <(/reference/configuration-options)>`"
    replace: ":manual:`\\1 <\\2>`"
---
source: includes/steps-configure-windows-service-for-mongodb.yaml
transform:
  regex: ":doc:`(.*) <(/reference/configuration-options)>`"
  replace: ":manual:`\\1 <\\2>`"
---
source: includes/steps-create-manually-windows-service-for-mongodb.yaml
transform:
  regex: ":doc:`(.*) <(/reference/configuration-options)>`"
  replace: ":manual:`\\1 <\\2>`"
---
source: includes/steps-run-mongodb-on-windows.yaml
transform:
  regex: ":doc:`(.*) <(.*)>`"
  replace: ":manual:`\\1 <\\2>`"
---
source: includes/list-mongodb-org-packages.rst
transform:
  regex: ":doc:`(.*) <(.*)>`"
  replace: ":manual:`\\1 <\\2>`"
---
source: core/data-modeling-introduction.txt
target: includes/excerpt-data-modeling-introduction.rst
truncate:
  start-after: .. start-primer-excerpt
  end-before: ".. end-primer-excerpt"
transform:
  regex: ":doc:`(.*) <(.*)>`"
  replace: ":manual:`\\1 <\\2>`"
---
source: administration/production-notes.txt
target: core/production-notes.rst
transform:
  regex: ":doc:`(.*) <(.*)>`"
  replace: ":manual:`\\1 <\\2>`"
---
source: core/replication-introduction.txt
target: core/replication.rst
transform:
  regex: ":doc:`(.*) <(.*)>`"
  replace: ":manual:`\\1 <\\2>`"
truncate:
  start-after: ".. start-primer-here"
  end-before: ".. end-primer-here"
---
source: core/sharding-introduction.txt
target: core/sharding.rst
transform:
  regex: ":doc:`(.*) <(.*)>`"
  replace: ":manual:`\\1 <\\2>`"
truncate:
  start-after: ".. start-primer-here"
---
source: core/indexes-introduction.txt
target: includes/introduction-indexes.rst
truncate:
  start-after: ".. start-primer-introduction"
  end-before: ".. end-primer-introduction"
---
source: core/indexes-introduction.txt
target: includes/excerpt-indexes-optimization.rst
truncate:
  start-after: ".. start-primer-index-optimization"
  end-before: ".. end-primer-index-optimization"
---
source: core/aggregation-introduction.txt
target: includes/introduction-aggregation.rst
truncate:
  start-after: ".. start-primer-excerpt"
  end-before: ".. end-primer-excerpt"
...