title:
  text: Change configuration file.
  character: "`"
stepnum: 1
pre: |
  To configure your :program:`mongod` or :program:`mongos` instance to use
  FIPS mode, shut down the instance and update the configuration file with
  the following setting:
ref: "change-config-file"
action:
  language: yaml
  code: |
     net:
        ssl:
           FIPSMode: true
---
title:
  text: "Start :program:`mongod` or :program:`mongos` instance with configuration file."
  character: "`"
stepnum: 2
ref: "start-service-config-file"
pre: "For example, run this command to start the  :program:`mongod` instance with its configuration file:"
action:
  language: javascript
  code: |
     mongod --config /etc/mongodb.conf
...