file: /tutorial/model-data-for-atomic-operations
description: |
   Illustrates how embedding fields related to an atomic update within
   the same document ensures that the fields are in sync.
---
file: /tutorial/model-data-for-keyword-search
description: |
   Describes one method for supporting keyword search by storing
   keywords in an array in the same document as the text field.
   Combined with a multi-key index, this pattern can support
   application's keyword search operations.
---
file: /tutorial/model-monetary-data
description: |
   Describes two methods to model monetary data in MongoDB.
---
file: /tutorial/model-time-data
description: |
   Describes how to deal with local time in MongoDB.
...
