target: push
paths:
  remote: /data/sites/docs
  local: public
  static: [ 'manual', '.htaccess', 'sitemap.xml', 'robots.txt', 'master/sitemap.xml.gz' ]
options: [ 'branched', 'recursive' ]
env: publication
dependency: push-if-up-to-date
---
target: push-with-delete
paths:
  remote: /data/sites/docs
  local: public
  static: [ 'manual', '.htaccess','sitemap.xml', 'robots.txt', 'master/sitemap.xml.gz' ]
options: [ 'delete', 'branched', 'recursive' ]
env: publication
dependency: publish
---
target: stage
paths:
  remote: /srv/public/test
  local: public
  static: [ 'manual', 'sitemap.xml', 'robots.txt', 'master/sitemap.xml.gz' ]
options: [ 'branched', 'recursive' ]
env: staging
dependency: stage-if-up-to-date
---
target: stage-with-delete
paths:
  remote: /srv/public/test
  local: public
  static: [ 'manual', 'robots.txt', 'master/sitemap.xml.gz' ]
options: [ 'delete', 'branched', 'recursive' ]
env: staging
dependency: publish
...
